repos:


  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.14
    hooks:
      - id: insert-license
        files: \.(js|jsx)$
        args: [
          '--license-filepath=COPYRIGHT',
          '--comment-style=/*| *| */',
        ]
