# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm ci
      - name: Create .env file
        run: echo '${{ secrets.ENV }}' > .env
      - name: Build and Run Docker Image
        run: |
          docker build -t web .
          docker run web
      - name: Create users.js
        run: echo '${{ secrets.USER_CREDENTIALS }}' > tests/users.js
      - run: npm run test:local
