# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create .env file
        run: echo '${{ secrets.ENV }}' > .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Run Docker Image
        run: |
          docker build -t web .
          docker run -d -p 3000:3000 web
          sleep 480s
      - name: Create users.js
        run: echo '${{ secrets.USER_CREDENTIALS }}' > tests/users.js
      - run: npm run test:local
      - name: Install NYC and generate coverage report 
        run: |
          npm i -g nyc
          nyc report --reporter=json-summary
      # - name: Download CodeCov uploader ##linux specific##
      #   run: curl -Os https://uploader.codecov.io/latest/linux/codecov chmod +x codecov ./codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: './coverage',
          files: './coverage-summary.json'
          flags: 'e2e poc'

