# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies 
        run: |
          npm ci
          npm install -g serve pm2
      - name: Create env file from environment secrets
        run: |
          echo '${{ secrets.ENV }}' > .env
          cat .env
      - name: Build and serve
        run: |
          CI=false npm run build-dev
          pm2 serve build 3000 --spa
      - name: Create users.js
        run: |
          echo '${{ secrets.USER_CREDENTIALS }}' > e2e/users.js
          cat e2e/users.js
      - run: npm test
